"""empty message

Revision ID: 344a86a70a9a
Revises: 
Create Date: 2021-11-26 00:47:17.230511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344a86a70a9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('studios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('studio_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studio_name')
    )
    op.create_table('anime',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anime_title', sa.String(length=128), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_title')
    )
    op.create_table('anime_genres',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('anime_id', 'genre_id')
    )
    op.create_table('main_characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_name', sa.String(length=128), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_characters')
    op.drop_table('anime_genres')
    op.drop_table('anime')
    op.drop_table('studios')
    op.drop_table('genres')
    # ### end Alembic commands ###
